version: '3'

services:
  server:
    image: br11/mean_crud_server:0.0.2
    ports:
      - "8080:8080"
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mongo

  
  mongo:
    image: mongo:3.4.9
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
      - logs:/var/log
    networks:
      - backend

volumes:
  data:
  logs:

networks:
  backend:
    driver: overlay

#networks:
#  backend:
#    external:
#      name: backend

#networks:
#  backend:
#    driver: overlay
#    driver_opts:
#      foo: "1"
#      bar: "2"
