version: '3'

services:
  server:
    image: br11/mean_crud_server:0.0.1
    build: .
    ports:
    - "8080:8080"
    links:
    - mongo
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 2
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s

  mongo:
    image: mongo:3.4.9
    ports:
    - "27017:27017"
    volumes:
    - /code:/code
    - ~/projects/mean_crud_server/data/db:/data/db
    - ~/projects/mean_crud_server/data/log:/var/log
    networks:
      - backend

volumes:
  /code:
  ~/projects/mean_crud_server/data/db:
  ~/projects/mean_crud_server/data/log:

networks:
  backend:
    driver: overlay
    driver_opts:

#networks:
#  backend:
#    external:
#      name: backend

#networks:
#  backend:
#    driver: overlay
#    driver_opts:
#      foo: "1"
#      bar: "2"
