version: '3'
services:
  server:
    build: .
    ports:
    - "8080:8080"
    links:
    - mongo
    volumes:
    - \Users\marcio.luis.da.silva\data\db:/data/db
  mongo:
    image: mongo:3.4.9
    ports:
    - "27017:27017"
    volumes:
    - .:/code
    - data:/var/log
volumes:
  logvolume01: {}