version: '3'

services:
  server:
    image: br11/mean_crud_server:latest
    ports:
    - "8080:8080"
    links:
      - mongo
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 5
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s

  mongo:
    image: mongo:3.4.9
    ports:
    - "27017:27017"
    volumes:
    - data:/data/db
    - logs:/var/log
    networks:
      - backend
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s

volumes:
  data:
  logs:

networks:
  backend:
    driver: overlay
    driver_opts:

#networks:
#  backend:
#    external:
#      name: backend

#networks:
#  backend:
#    driver: overlay
#    driver_opts:
#      foo: "1"
#      bar: "2"
